FE/Controllers/AdvisorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FE.Data;
using FE.Models;
using FE.Models.Domain;


namespace FE.Controllers
{
    public class AdvisorController:Controller
    {
        private readonly ApplicationDbContext dbcontext;

        public AdvisorController(ApplicationDbContext dbcontext)
        {
            this.dbcontext = dbcontext;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var advisors = await dbcontext.Advisor.ToListAsync();
            return View(advisors);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> Add(AddAdvisorViewModel sa)
        {
            var advisors = new StyleAdvisor
            {
                Id = Guid.NewGuid(),
                Name = sa.Name,
                LastName= sa.LastName,
                Email = sa.Email,
                Age= sa.Age,
                Experience=sa.Experience,
                StyleType=sa.StyleType, 
                Phone = sa.Phone,
                DateOfBirth = sa.DateOfBirth,
            };

            if(sa.Image != null)
            {
                // Convert image to byte array
                using (var stream = new MemoryStream())
                {
                    await sa.Image.CopyToAsync(stream);
                    advisors.Image = stream.ToArray();
                }
            }



            await dbcontext.Advisor.AddAsync(advisors);
            await dbcontext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {

            var advisor= await dbcontext.Advisor.FirstOrDefaultAsync(x => x.Id == id);

            if (advisor != null)
            {
                var viewModel = new UpdateAdvisorViewModel()
                {

                    Id = advisor.Id,
                    Name = advisor.Name,
                    LastName = advisor.LastName,
                    Email = advisor.Email,
                    Age= advisor.Age,
                    Experience=advisor.Experience,
                    StyleType=advisor.StyleType,
                    Phone = advisor.Phone,
                    DateOfBirth = advisor.DateOfBirth,
                };
                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("Index");

        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateAdvisorViewModel model)
        {
            
            
            var advisor = await dbcontext.Advisor.FindAsync(model.Id);
            if (advisor != null)
            {
                advisor.Name = model.Name;
                advisor.LastName = model.LastName;    
                advisor.Email = model.Email;
                advisor.Age= model.Age;
                advisor.Experience= model.Experience;
                advisor.StyleType = model.StyleType;
                advisor.Phone = model.Phone;
                advisor.DateOfBirth = model.DateOfBirth;
                advisor.Id= model.Id;
                if (model.Image != null)
                {
                    // Convert image to byte array
                    using (var stream = new MemoryStream())
                    {
                        await model.Image.CopyToAsync(stream);
                        advisor.Image = stream.ToArray();
                    }
                }

                await dbcontext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        [HttpPost]

        public async Task<IActionResult> Delete(UpdateAdvisorViewModel model)
        {
            var advisor = await dbcontext.Advisor.FindAsync(model.Id);

            if (advisor != null)
            {
                dbcontext.Advisor.Remove(advisor);
                await dbcontext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }

       /* public async Task<IActionResult> GetImage(Guid id)
        {
            var advisor = await dbcontext.Advisor.FirstOrDefaultAsync(x => x.Id == id);
            if (advisor == null || advisor.Image == null)
            {
                return NotFound();
            }

            return File(advisor.Image, "image/jpeg");
        }*/
    }
}

FE/ViewComponents/AdvisorListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FE.Data;
using FE.Models.Domain;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace FE.ViewComponents
{
    public class AdvisorListViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext dbcontext;

        public AdvisorListViewComponent(ApplicationDbContext dbcontext)
        {
            this.dbcontext = dbcontext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var advisors = await dbcontext.Advisor
                .ToListAsync();

            return View(advisors);
        }
    }
}

FE/Views/Shared/Partial1.cshtml
<link rel="stylesheet" href="/css/style.css">




<table id="advisor">
    <thead>
        <tr>
            <td>Photo</td>
            <td>Id</td>
            <td>Name</td>
            <td>LastName</td>
            <td>Email</td>
            <td>Age</td>     
            <td>Date Of Birth</td>
            <td>Experience</td>
            <td>Style Type</td>
            <td>Phone</td>
            <td>Update</td>
        </tr>
    </thead>

    <tbody>
        @foreach (var advisor in Model)
        {
                <tr>
                <td><img src="data:image/png;base64,@Convert.ToBase64String(@advisor.Image)" style="width:100px;height:120px;" alt="Resim" /></td>
                    <td>@advisor.Id</td>
                    <td>@advisor.Name</td>
                    <td>@advisor.LastName</td>
                    <td>@advisor.Email</td>
                    <td>@advisor.Age</td>  
                    <td>@advisor.DateOfBirth.ToString("dd-MM-yyyy")</td>
                    <td>@advisor.Experience</td>
                    <td>@advisor.StyleType</td>
                    <td>@advisor.Phone</td>
                    <td><a href="Advisor/View/@advisor.Id">View</a></td>
                </tr>
        }
    </tbody>
</table>


@await Component.InvokeAsync("AdvisorList")

FE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FE</title>
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />-->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FE.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shared/Layout.cshtml.css" asp-append-version="true" />
    <link rel="stylesheet" href="/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Anton&family=Bebas+Neue&family=Concert+One&family=Cookie&family=Righteous&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">

</head>
<body>
    
    <header>
      
        <nav>
        <h3 id="writing" style="font-family: 'Cookie', cursive;">Marie CLarie</h3>
        <img id="btrfly" src="/css/butterfly.gif" alt="">
        <ul id="contents" style="font-family: 'Alfa Slab One', cursive;
            font-family: 'Anton', sans-serif;
            font-family: 'Bebas Neue', cursive;
            font-family: 'Concert One', cursive;
            font-family: 'Cookie', cursive;
            font-family: 'Righteous', cursive;">
            <li>
                <a asp-controller="Advisor" asp-action="Add" >Join Us</a>
            </li>

            <li>
                 <a asp-controller="Advisor" asp-action="Index">Advisor List</a>
            </li>
            
            <li>
                <a asp-controller="Home" asp-action="OutfitStyles">Outfit Styles</a>
            </li>

            <li>
                <a asp-controller="Home" asp-action="AboutUs">About Us</a>
            </li>

            <li>
                <a asp-controller="Home" asp-action="Index">Home Page</a>
            </li>
            
            
        </ul>

    </nav>
        @await RenderSectionAsync("header", required:false)

       <!-- <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <!--  <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>-->
                <!--<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>-->
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            </main>
     </div>

    <!--footer id="ab1">
        <div class="container">
            &copy; @DateTime.Now.Year - Marie Clarie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>-->

   
    <!-- <script src="~/lib/jquery/dist/jquery.min.js"></script>
     <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>-->
    @await RenderSectionAsync("Scripts", required:false)
</body>
</html>